app/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from accounts import views

urlpatterns = [
    path('send_login_email', views.send_login_email, name='send_login_email'),
    path('login', views.login, name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

app/lists/urls.py
from django.urls import path
from lists import views

urlpatterns = [
    path('new', views.new_list, name='new_list'),
    path('<int:list_id>/', views.view_list, name='view_list'),
    path('users/<str:email>/', views.my_lists, name='my_lists'),
    path('<int:list_id>/share', views.share_list, name='share_list'),
]

app/main/urls.py
from django.urls import path, include
from lists import views as list_views
from lists import api_urls

urlpatterns = [
    path('', list_views.home_page, name='home'),
    path('lists/', include('lists.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include(api_urls))
]

app/accounts/models.py
from django.db import models
import uuid

class User(models.Model):
    email = models.EmailField(unique=True, primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.UUIDField(default=uuid.uuid4)

app/lists/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class List(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='shared_with'
    )

    def get_absolute_url(self):
        return reverse('view_list', args=(self.id,))

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    @property
    def name(self):
        return self.item_set.first().text

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

app/lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item, List

DUPLICATE_ITEM_ERROR = "You've already got this in your list"
EMPTY_ITEM_ERROR = "You can't have an empty list item"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(
                attrs={
                    'placeholder': 'Enter a to-do item',
                    'class': 'form-control input-lg'
                }
            )
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)


class NewListForm(ItemForm):

    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])


class ShareForm(forms.Form):
    sharee = forms.EmailField()

app/accounts/views.py
from django.contrib import auth
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.shortcuts import reverse

from accounts.models import Token

def send_login_email(request):
    email = request.POST.get('email')
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + f'?token={token.uid}'
    )
    message_body = f'Use this link to log in:\n\n{url}'

    send_mail(
      'Your login link for Superlists',
      message_body,
      'tddcompython@gmail.com',
      [email]
    )

    messages.success(
        request,
        "Check your email, we've sent you a link you can use to log in."
    )

    return redirect('/')


def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

app/lists/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render

from lists.forms import ShareForm
from lists.forms import NewListForm
from lists.forms import ExistingListItemForm

from lists.forms import ItemForm
from lists.models import List


User = get_user_model()

def home_page(request):
    return render(request, 'home.html', {"form": ItemForm()})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)

    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)

    return render(request, 'list.html', {"list": list_, "form": form})

def new_list(request):
    form = NewListForm(data=request.POST)

    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {"form": form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {"owner": owner})


def share_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ShareForm(data=request.POST)
    if form.is_valid():
        user, _ = User.objects.get_or_create(email=request.POST['sharee'])
        list_.shared_with.add(user)
    return redirect(list_)

app/templates/base.html
<html>
  <head>
    <title>To-Do lists</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">

      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Superlists</a>
          {% if user.email %}
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="navbar-text">Logged in as {{ user.email }}</li>
              <li><a href="{% url 'logout' %}">Log out</a></li>
            </ul>
          {% else %}
            <form
              class="navbar-form navbar-right"
              method="POST"
              action="{% url 'send_login_email' %}"
            >
              <span>Enter email to log in:</span>
              <input class="form-control" name="email" type="email" />
              {% csrf_token %}
            </form>
          {% endif %}
        </div>
      </nav>

      {% if messages %}
        <div class="row">
          <div class="col-md-6 col-md-offset-3 mx-auto ">
            {% for message in messages %}
              {% if message.level_tag == 'success' %}
                <div class="alert alert-success">{{ message }} </div>
              {% else %}
                <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      {% endif %}

      <div class="row">
        <div class="col-md-6 col-md-offset-3 mx-auto jumbotron">
          <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            {% block list_form %}
              <form
                id="id_item_form"
                method="post"
                action="{% block form_action %}{% endblock %}"
                class="mt-3"
              >
                {{ form.text }}
                {% csrf_token %}
                  <div class="form-group has-error">
                    <div class="help-block">
                      {% if form.errors %}
                        {{ form.text.errors }}
                      {% endif %}
                    </div>
                  </div>
              </form>
          {% endblock %}
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3 mx-auto">
          {% block table %}
          {% endblock %}
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3 mx-auto">
          {% block extra_content %}
          {% endblock %}
        </div>
      </div>

    </div>
  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script src="/static/list.js"></script>

  {% block scripts %}
  {% endblock %}
</html>

app/templates/home.html
{% extends "base.html" %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list'%}{% endblock %}

app/templates/list.html
{% extends "base.html" %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
  <table id="id_list_table" class="table">
  </table>

  {% if list.owner %}
    <p>List owner: <span id="id_list_owner">{{ list.owner.email }}</span><p>
  {% endif %}

{% endblock %}


{% block extra_content %}

  <div>
    <h2>List shared with:</h2>
    <ul class="list-sharee">
      {% for user in list.shared_with.all %}
        <li>{{ user.email }}</li>
      {% endfor %}
    </ul>
  </div>

  <form
    class="navbar-form navbar-right"
    method="POST"
    action="{% url 'share_list' list.id %}"
  >
    <span>Share with a friend</span>
    <input
      class="form-control"
      name="sharee"
      type="email"
      placeholder='your-friend@example.com'
    />
    {% csrf_token %}
  </form>
{% endblock %}


{% block scripts %}
  <script>
    $(document).ready(function () {
      var url = "{% url 'api_list' list.id %}"
      console.log(url)
      window.Superlists.initialize(url)
    })
  </script>
{% endblock %}

app/templates/my_lists.html
{% extends "base.html" %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
  <h2>{{ owner.email }}'s lists</h2>
  <ul>
    {% for list in owner.list_set.all %}
      <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    {% endfor %}
  </ul>

  <h2>List shared by others users</h2>
  <ul>
    {% for list in owner.shared_with.all %}
      <li>
        <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
        ({{ list.owner.email }})
      </li>
    {% endfor %}
  </ul>
{% endblock %}